## THIS FILE DEFINES THE KIT HEAD STATE/COMMAND

## 0-5 joints before eyes
float32[] joints
float32[] velocity
float32[] acceleration
float32[] effort
float32[] stiffness

# left eye joint
float32 jointsLEye
float32 velocityLEye
float32 accelerationLEye
float32 effortLEye
float32 stiffnessLEye

# right eye joint
float32 jointsREye
float32 velocityREye
float32 accelerationREye
float32 effortREye
float32 stiffnessREye

